# Generated by Django 4.2.3 on 2023-09-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestion', '0003_rename_producto_no_producto_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='detalle',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
